import { StyleSheet } from "react-native";

export const utilities = {
  fontSize: {
    xl: 32,
    lg: 24,
    md: 18,
    sm: 14,
    xs: 10,
  },
  fontColor: {
    gray900: "#1a202c",
    gray800: "#2d3748",
    gray700: "#4a5568",
    gray600: "#718096",
    gray500: "#a0aec0",
    gray400: "#cbd5e0",
    gray300: "#e2e8f0",
  },
  lineHeight: {
    xl: 32 * 1.5,
    lg: 24 * 1.5,
    md: 18 * 1.5,
    sm: 14 * 1.5,
    xs: 10 * 1.5,
  },
  padding: {
    xl: 24,
    lg: 18,
    md: 14,
    sm: 10,
    xs: 8,
  },
  margin: {
    xl: 24,
    lg: 18,
    md: 16,
    sm: 12,
    xs: 8,
  },
  color: {
    primary: "#FF0000",
    secondary: "",
    tertiary: "",
    lightGray: "#808080",
    extraLightGray: "#7d7d7d",
  },
  iconSize: {
    lg: 32,
    md: 24,
    sm: 18,
  },
  radius: {
    xl: 24,
    lg: 18,
    md: 16,
    sm: 12,
    xs: 8,
  },
};

export const globalStyle = StyleSheet.create({
  logo: {
    fontSize: 35,
    marginBottom: utilities.margin.md,
    fontWeight: "700",
    color: utilities.color.primary,
  },
  logoSm: {
    fontSize: 20,
    color: utilities.color.primary,
  },
  textInput: {
    marginBottom: utilities.margin.md,
    color: utilities.fontColor.gray800,
    fontSize: utilities.fontSize.md,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: utilities.color.primary,
    padding: utilities.padding.md,
    width: "100%",
    textAlignVertical: "top",
  },
  textInputSm: {
    marginBottom: utilities.margin.sm,
    color: utilities.fontColor.gray800,
    fontSize: utilities.fontSize.sm,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: utilities.color.primary,
    padding: utilities.padding.xs,
    width: "100%",
    textAlignVertical: "top",
  },
  primaryButton: {
    backgroundColor: utilities.color.primary,
    padding: utilities.padding.md,
    borderRadius: 16,
    width: "50%",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: utilities.margin.lg,
  },
  primarySmButton: {
    backgroundColor: utilities.color.primary,
    padding: utilities.padding.xs,
    paddingHorizontal: 20,
    borderRadius: 12,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: utilities.margin.xs,
  },
  textButton: {
    color: "white",
    fontSize: utilities.fontSize.sm,
    fontWeight: "600",
  },
  textError: {
    color: utilities.fontColor.gray800,
    fontSize: utilities.fontSize.md,
    marginVertical: 5,
    textAlign: "center",
  },
});
